version: '3.1'
services:
  mongo:
    container_name: middleware-api-mongodb-development
    image: mongo:latest
    ports:
      - 27017:27017
networks:
  default:
    name: middleware-api-mongodb-development-network