swagger:
  outputDirectory: ./dist
  entryFile: 
    - ./src/controller/*
    - ./src/api/potres2020/*
  outputFormat: OpenApi_3
  name: middleware-api
  description: Middleware API for the Potres2020 ecosystem
  license: AGPL-3.0-only
  produces: [application/json]
  version: 0.0.1
  securityDefinitions:
    default:
      type: apiKey
      in: header
      name: Authorization
    secondAuthenticator:
      type: apiKey
      in: header
      name: Authorization
